version: '3.8'

services:
  whisper-gui:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./models:/app/models  # Persist downloaded models
      - ./outputs:/app/outputs  # Store output files
      - ./configs:/app/configs  # Configuration files
      - ./temp:/app/temp  # Temporary files
    environment:
      - PYTHONUNBUFFERED=1
    platform: linux/arm64  # Specify platform for M1/M2/M3 Macs
    user: "${UID:-1000}:${GID:-1000}"  # Run as current user
    init: true  # Proper signal handling 