version: '3.8'

services:
  whisper-gui:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./models:/app/models  # Persist downloaded models
      - ./outputs:/app/outputs  # Store output files
      - ./configs:/app/configs  # Configuration files
    platform: linux/arm64  # Specify platform for M1/M2/M3 Macs 