channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip=23.3.1
  - python=3.10.13
  - pip:
      - ctranslate2>=4.5.0
      - faster-whisper>=1.1.1
      - nltk>=3.9.1
      - numpy>=2.0.2
      - onnxruntime==1.19
      - pandas>=2.2.3
      - pyannote-audio>=3.3.2
      - torch>=2.5.1
      - torchaudio>=2.5.1
      - transformers>=4.48.0
      - gradio==4.37.2
      - gradio-client==1.0.2
